# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'adoToDockerhub'
    repository: 'hyukjun/webscrapper'
    command: 'buildAndPush'
    Dockerfile: 'v2/Dockerfile'
    buildContext: 'v2'
    tags: '$(VERSION)'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'deployToWebapp'
    appName: 'hyukjun-webapps'
    containers: 'hyukjun/webscrapper:$(VERSION)'
    appSettings: '-WEBSITES_PORT 5000'